"""add_columns_to_order_status_history

Revision ID: 7d454f0e93a3
Revises: 273b4e1d03f5
Create Date: 2026-06-23 18:17:10.464005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d454f0e93a3'
down_revision: Union[str, Sequence[str], None] = '273b4e1d03f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_status_history', sa.Column('changed_by_user_id', sa.UUID(), nullable=True))
    op.add_column('order_status_history', sa.Column('changed_by_role', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'order_status_history', 'users', ['changed_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_status_history', type_='foreignkey')
    op.drop_column('order_status_history', 'changed_by_role')
    op.drop_column('order_status_history', 'changed_by_user_id')
    # ### end Alembic commands ###
