"""Initial schema

Revision ID: bc82980c61bf
Revises: 
Create Date: 2026-06-19 00:04:55.354905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc82980c61bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_buyer_addresses_buyer_id'), table_name='buyer_addresses')
    op.drop_constraint(op.f('cart_items_cart_id_product_id_key'), 'cart_items', type_='unique')
    op.drop_index(op.f('idx_cart_items_cart_product'), table_name='cart_items')
    op.drop_index(op.f('idx_cart_items_product_id'), table_name='cart_items')
    op.create_unique_constraint('uq_cart_product', 'cart_items', ['cart_id', 'product_id'])
    op.alter_column('carts', 'buyer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('idx_carts_buyer_id'), table_name='carts')
    op.drop_index(op.f('idx_delivery_jobs_driver_id'), table_name='delivery_jobs')
    op.drop_index(op.f('idx_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('idx_order_status_history_order_id'), table_name='order_status_history')
    op.drop_index(op.f('idx_orders_buyer_id'), table_name='orders')
    op.drop_index(op.f('idx_orders_store_id'), table_name='orders')
    op.drop_index(op.f('idx_product_images_product_id'), table_name='product_images')
    op.drop_index(op.f('idx_unique_primary_image_per_product'), table_name='product_images', postgresql_where='(is_primary = true)')
    op.drop_index(op.f('idx_active_products'), table_name='products', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_products_store_id'), table_name='products')
    op.drop_index(op.f('idx_stores_seller_id'), table_name='stores')
    op.drop_index(op.f('idx_wallet_transactions_wallet_id'), table_name='wallet_transactions')
    op.alter_column('wallets', 'buyer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('idx_wallets_buyer_id'), table_name='wallets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_wallets_buyer_id'), 'wallets', ['buyer_id'], unique=False)
    op.alter_column('wallets', 'buyer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('idx_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
    op.create_index(op.f('idx_stores_seller_id'), 'stores', ['seller_id'], unique=False)
    op.create_index(op.f('idx_products_store_id'), 'products', ['store_id'], unique=False)
    op.create_index(op.f('idx_active_products'), 'products', ['store_id'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_unique_primary_image_per_product'), 'product_images', ['product_id'], unique=True, postgresql_where='(is_primary = true)')
    op.create_index(op.f('idx_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.create_index(op.f('idx_orders_store_id'), 'orders', ['store_id'], unique=False)
    op.create_index(op.f('idx_orders_buyer_id'), 'orders', ['buyer_id'], unique=False)
    op.create_index(op.f('idx_order_status_history_order_id'), 'order_status_history', ['order_id'], unique=False)
    op.create_index(op.f('idx_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('idx_delivery_jobs_driver_id'), 'delivery_jobs', ['driver_id'], unique=False)
    op.create_index(op.f('idx_carts_buyer_id'), 'carts', ['buyer_id'], unique=False)
    op.alter_column('carts', 'buyer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('uq_cart_product', 'cart_items', type_='unique')
    op.create_index(op.f('idx_cart_items_product_id'), 'cart_items', ['product_id'], unique=False)
    op.create_index(op.f('idx_cart_items_cart_product'), 'cart_items', ['cart_id', 'product_id'], unique=False)
    op.create_unique_constraint(op.f('cart_items_cart_id_product_id_key'), 'cart_items', ['cart_id', 'product_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_buyer_addresses_buyer_id'), 'buyer_addresses', ['buyer_id'], unique=False)
    # ### end Alembic commands ###
