"""split discounts into promos and vouchers

Revision ID: c0de3cf274b7
Revises: 7d454f0e93a3
Create Date: 2026-06-25 17:11:35.097417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0de3cf274b7'
down_revision: Union[str, Sequence[str], None] = '7d454f0e93a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vouchers',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_purchase', sa.Numeric(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('max_discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('remaining_usage', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='chk_voucher_amount'),
    sa.CheckConstraint('max_discount >= 0', name='chk_voucher_max_discount'),
    sa.CheckConstraint('min_purchase >= 0', name='chk_voucher_min_purchase'),
    sa.CheckConstraint('remaining_usage >= 0', name='chk_voucher_remaining_usage'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('promos',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount_percentage > 0 AND discount_percentage <= 100', name='chk_promo_percentage'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promos_store_id'), 'promos', ['store_id'], unique=False)
    op.create_table('promo_products',
    sa.Column('promo_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promo_id'], ['promos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('promo_id', 'product_id')
    )
    op.drop_constraint(op.f('orders_discount_id_fkey'), 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_discount_id'), table_name='orders')
    op.drop_column('orders', 'discount_id')
    op.drop_column('orders', 'discount_amount')
    op.drop_table('discounts')
    op.add_column('orders', sa.Column('promo_id', sa.BigInteger(), nullable=True))
    op.add_column('orders', sa.Column('voucher_id', sa.BigInteger(), nullable=True))
    op.add_column('orders', sa.Column('promo_discount_amount', sa.Numeric(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False))
    op.add_column('orders', sa.Column('voucher_discount_amount', sa.Numeric(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False))
    op.create_index(op.f('ix_orders_promo_id'), 'orders', ['promo_id'], unique=False)
    op.create_index(op.f('ix_orders_voucher_id'), 'orders', ['voucher_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'promos', ['promo_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'vouchers', ['voucher_id'], ['id'], ondelete='SET NULL')
    op.add_column('products', sa.Column('promo_price', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'promo_price')
    op.add_column('orders', sa.Column('discount_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('discount_amount', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_discount_id_fkey'), 'orders', 'discounts', ['discount_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_orders_voucher_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_promo_id'), table_name='orders')
    op.create_index(op.f('ix_orders_discount_id'), 'orders', ['discount_id'], unique=False)
    op.drop_column('orders', 'voucher_discount_amount')
    op.drop_column('orders', 'promo_discount_amount')
    op.drop_column('orders', 'voucher_id')
    op.drop_column('orders', 'promo_id')
    op.create_table('discounts',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('discount_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('expiry_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('remaining_usage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.CheckConstraint("discount_type::text = ANY (ARRAY['VOUCHER'::character varying, 'PROMO'::character varying]::text[])", name=op.f('discounts_discount_type_check')),
    sa.CheckConstraint('amount >= 0::numeric', name=op.f('discounts_amount_check')),
    sa.CheckConstraint('remaining_usage >= 0', name=op.f('discounts_remaining_usage_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('discounts_pkey')),
    sa.UniqueConstraint('code', name=op.f('discounts_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('promo_products')
    op.drop_index(op.f('ix_promos_store_id'), table_name='promos')
    op.drop_table('promos')
    op.drop_table('vouchers')
    # ### end Alembic commands ###
